ingest:
  endpoints:
    foo:
      topic: foo
    bar:
      topic: bar
      schema:
        path: /schema/test.avcs

    baz:
      topic: baz
      schema:
        value: '{"namespace": "example.avro", "type": "record", "name": "User",  "fields": [ {"name": "name", "type": "string"}]}'

