server:
  port: 9000

kafka:
  bootstrap.servers: localhost:9092
  schema.registry.url: http://localhost:8081
  producer:
    auto.register.schemas: false
    retries: 5
    acks: all

ingest:
  endpoints:
    foo:
      topic: json-topic
      blocking: false

#    baz:
#      topic: avro-topic
#      schema:
#        value: '{"type":"record","name":"schema1","namespace":"test","fields":[{"name":"name","type":"string"},{"name":"age","type":"int"}]}'
#
