server:
  port: 9000

kafka:
  properties:
    bootstrap-servers: localhost:9092
    schema.registry.url: http://localhost:8081
    auto.register.schemas: false

ingest:
  endpoints:
    foo:
      topic: foo
    baz:
      topic: avro-topic
      schema:
        value: '{"type":"record","name":"schema1","namespace":"test","fields":[{"name":"name","type":"string"},{"name":"age","type":"int"}]}'

#ingest:
#  endpoints:
#    foo:
#      topic: foo
#    bar:
#      topic: bar
#      schema:
#        path: /schema/test.avcs
#
#    baz:
#      topic: baz
#      schema:
#        value: '{"namespace": "example.avro", "type": "record", "name": "User",  "fields": [ {"name": "name", "type": "string"}]}'

