server:
  port: 9000

kafka:
  properties:
    bootstrap-servers: localhost:9092
    schema.registry.url: localhost:8082

ingest:
  endpoints:
    foo:
      topic: foo
    baz:
      topic: baz
      schema:
        value: '{"namespace": "example.avro", "type": "record", "name": "User",  "fields": [ {"name": "name", "type": "string"}]}'

#ingest:
#  endpoints:
#    foo:
#      topic: foo
#    bar:
#      topic: bar
#      schema:
#        path: /schema/test.avcs
#
#    baz:
#      topic: baz
#      schema:
#        value: '{"namespace": "example.avro", "type": "record", "name": "User",  "fields": [ {"name": "name", "type": "string"}]}'

